import GKR.Src.Wiring
import GKR.Src.LinearizeFunction
import GKR.Src.Circuit
import GKR.Src.Linearize
import GKR.Properties.Circuit
import GKR.Properties.LinearizeFunction -- for toPoint

open CPoly CPoly.CMvPolynomial


/--
Helper. Used for proving the agreement on the cube in then theorem below.
-/
lemma gluePoint_toPoint {k : ℕ}
{F : Type} [Field F]
(z x y : Index k) :
gluePoint (toPoint (F := F) z) (toPoint x) (toPoint y)
      = toPoint (glueIndex z x y) := by
funext arg
induction arg using Fin.addCases with
| left i =>
  simp only [gluePoint, glueIndex, toPoint, Fin.append_left]
| right j =>
  induction j using Fin.addCases with
  | left i  =>
      simp only [gluePoint, glueIndex, toPoint, Fin.append_right, Fin.append_left]
  | right i =>
    simp only [gluePoint, glueIndex, toPoint, Fin.append_right]


theorem layer_sum_mle_cube
{k d : ℕ} {F : Type} [Field F] [BEq F] [LawfulBEq F]
(c : Circuit k d) (input : Index k → F) (l : Fin d) (z : Index k)
: (linearizeFunction (layerValues c input l.castSucc)).eval (toPoint z)
= ∑ bb : Index k, ∑ cc : Index k,
    ( (addTilde F c l).eval (gluePoint (toPoint z) (toPoint bb) (toPoint cc))
        * ( (linearizeFunction (layerValues c input l.succ)).eval (toPoint bb)
          + (linearizeFunction (layerValues c input l.succ)).eval (toPoint cc) )
    + (mulTilde F c l).eval (gluePoint (toPoint z) (toPoint bb) (toPoint cc))
        * ( (linearizeFunction (layerValues c input l.succ)).eval (toPoint bb)
          * (linearizeFunction (layerValues c input l.succ)).eval (toPoint cc) ) ) := by
        unfold addTilde mulTilde
        simp only [gluePoint_toPoint, ← function_linearization_agrees,
        part₀_glueIndex, part₁_glueIndex, part₂_glueIndex]
        exact layer_values_eq_sum F c l input z

/--
Evaluating a linearized function at any point is equal to the evaluation
of the lagrange sum
-/
lemma eval_linearizeFunction
{k : ℕ}
{F : Type} [Field F] [BEq F] [LawfulBEq F]
(f : Index k → F)
(r : Fin k → F) :
  (linearizeFunction f).eval r = ∑ w : Index k, f w * eval r  (∏ i, chi i w F)
:= by
  unfold linearizeFunction
  rw [eval_sum_eq_sum_eval]
  simp only [eval_mul]
  simp only [eval_C]


lemma sum_index_glue {k : ℕ} {M : Type} [AddCommMonoid M]
    (g : Index (k + (k + k)) → M) :
    ∑ w, g w = ∑ z : Index k, ∑ x : Index k, ∑ y : Index k, g (glueIndex z x y) := by
  rw [← Equiv.sum_comp glueEquiv g]
  rw [Fintype.sum_prod_type]
  simp only [Fintype.sum_prod_type]
  rfl


/--
Helpers for proving stuff about chi generated by an llm
-/
lemma eval_chi_point
{k : ℕ}
{F : Type} [Field F] [BEq F] [LawfulBEq F]
    (s : Fin k) (w : Index k) (p : Fin k → F) :
    eval p (chi s w F) = if w s then p s else 1 - p s := by
  unfold chi
  cases hw : w s <;> simp [eval_X, eval_sub, eval_one]

lemma chi_block₀ {k : ℕ} {F : Type} [Field F] [BEq F] [LawfulBEq F]
    (z x y : Index k) (a b c : Fin k → F) (i : Fin k) :
    eval (gluePoint a b c) (chi (Fin.castAdd (k + k) i) (glueIndex z x y) F)
      = eval a (chi i z F) := by
  rw [eval_chi_point, eval_chi_point]
  simp only [glueIndex, gluePoint, Fin.append_left]

lemma chi_block₁ {k : ℕ} {F : Type} [Field F] [BEq F] [LawfulBEq F]
    (z x y : Index k) (a b c : Fin k → F) (i : Fin k) :
    eval (gluePoint a b c) (chi (Fin.natAdd k (Fin.castAdd k i)) (glueIndex z x y) F)
      = eval b (chi i x F) := by
  rw [eval_chi_point, eval_chi_point]
  simp only [glueIndex, gluePoint, Fin.append_right, Fin.append_left]

lemma chi_block₂ {k : ℕ} {F : Type} [Field F] [BEq F] [LawfulBEq F]
    (z x y : Index k) (a b c : Fin k → F) (i : Fin k) :
    eval (gluePoint a b c) (chi (Fin.natAdd k (Fin.natAdd k i)) (glueIndex z x y) F)
      = eval c (chi i y F) := by
  rw [eval_chi_point, eval_chi_point]
  simp only [glueIndex, gluePoint, Fin.append_right]

/--
 The basis polynomial factorises across the three blocks.
-/
lemma chi_prod_glue {k : ℕ} {F : Type} [Field F] [BEq F] [LawfulBEq F]
    (z x y : Index k) (a b c : Fin k → F) :
    (∏ s, eval (gluePoint a b c) (chi s (glueIndex z x y) F))
      = (∏ s, eval a (chi s z F)) * (∏ s, eval b (chi s x F))
        * (∏ s, eval c (chi s y F)) := by
  rw [Fin.prod_univ_add, Fin.prod_univ_add]
  rw [mul_assoc]
  congr 1
  · exact Finset.prod_congr rfl (fun i _ => chi_block₀ z x y a b c i)
  · congr 1
    · exact Finset.prod_congr rfl (fun i _ => chi_block₁ z x y a b c i)
    · exact Finset.prod_congr rfl (fun i _ => chi_block₂ z x y a b c i)

/--
TODO: review this
-/
lemma chi_prod_delta {k : ℕ} {F : Type} [Field F] [BEq F] [LawfulBEq F]
    (w m : Index k) :
    (∏ s, eval (toPoint m) (chi s w F)) = if w = m then 1 else 0 := by
  simp only [eval_chi, Finset.prod_boole, Finset.mem_univ, forall_const, ← funext_iff]


/--
TODO: review this
Rotate three nested sums: bring the innermost index to the outside. -/
lemma sum_rotate {k : ℕ} {M : Type} [AddCommMonoid M]
    (g : Index k → Index k → Index k → M) :
    (∑ a, ∑ b, ∑ c, g a b c) = ∑ c, ∑ a, ∑ b, g a b c := by
  rw [Finset.sum_congr rfl (fun a _ => Finset.sum_comm (f := fun b c => g a b c))]
  rw [Finset.sum_comm]

/--
we have proven the identity layer_values_eq_sum in GKR/Properties/Circuit.lean
now we prove this equality with multilinear extensionn taken on both sides
-/
theorem layer_sum_multilinear_extension
{k d : ℕ}
{F : Type} [Field F] [BEq F] [LawfulBEq F]
(c : Circuit k d)
(input : Index k → F)
(l : Fin d)
(r : Fin k → F)
: (linearizeFunction (layerValues c input l.castSucc)).eval r
= ∑ bb : Index k, ∑ cc : Index k,
    ( (addTilde F c l).eval (gluePoint r (toPoint bb) (toPoint cc))
        * ( (linearizeFunction (layerValues c input l.succ)).eval (toPoint bb)
          + (linearizeFunction (layerValues c input l.succ)).eval (toPoint cc) )
    + (mulTilde F c l).eval (gluePoint r (toPoint bb) (toPoint cc))
        * ( (linearizeFunction (layerValues c input l.succ)).eval (toPoint bb)
          * (linearizeFunction (layerValues c input l.succ)).eval (toPoint cc) ) ) := by
  unfold addTilde
  unfold mulTilde
  simp only [← function_linearization_agrees]
  rw [eval_linearizeFunction]
  simp only [layer_values_eq_sum]
  unfold linearizeFunction
  simp only [eval_sum_eq_sum_eval, eval_mul, eval_C, eval_prod_eq_prod_eval]
  simp only [sum_index_glue]
  simp only [chi_prod_glue]
  simp only [part₀_glueIndex, part₁_glueIndex, part₂_glueIndex, chi_prod_delta,
            mul_ite, mul_one, mul_zero, Finset.sum_ite_eq', Finset.mem_univ, if_true]
  simp only [Finset.sum_mul]
  simp only [← Finset.sum_add_distrib]
  conv_rhs => rw [sum_rotate]
  apply Finset.sum_congr rfl; intro z _
  apply Finset.sum_congr rfl; intro x _
  apply Finset.sum_congr rfl; intro y _
  ring
